# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/backend"
    schedule:
      interval: "daily" # Frequency of update checks (daily, weekly, or monthly)
      
  - package-ecosystem: "npm" # Use "npm" or "yarn" depending on your package manager
    directory: "/frontend" # Path to the frontend directory containing package.json
    schedule:
      interval: "daily" # Frequency of update checks
