---
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile

    # build:
    #   context: .
    # image: soma1337/pipe_dream:latest
    volumes:
      - "./backend:/app"
    env_file:
      - "./backend/testenv"
    depends_on:
      - timescale
    networks:
      - dbnet
      - webnet

  postgres:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5439:5432"  # Remapped to avoid conflict
    env_file:
      - "./backend/testenv"
    networks:
      - dbnet
  timescale:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - "db-data:/var/lib/postgresql/data"
    # remapped because it was conflicting with local postgres
    ports:
      - "5438:5432"
    env_file:
      - "./pull_data_service/testenv"
    networks:
      - dbnet

  python_program:
    build:
      context: ./pull_data_service/
      dockerfile: Dockerfile_python
    networks:
      - dbnet
    depends_on:
      - timescaledb
    env_file:
      - env
    restart: always


volumes:
  db-data:

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge


  # frontend:
  #   build:
  #     context: ./frontend
  #     # dockerfile: Dockerfile
  #
  #   # volumes:
  #   #   - ".:/app"
  #   ports:
  #     - "3000:3000"
  #   # build:
  #   #   context: .
  #   # image: soma1337/pipe_dream:latest
  #   env_file:
  #     - "./backend/testenv"
  #   depends_on:
  #     - timescale
  #     - backend
  #   networks:
  #     - dbnet
  #     - webnet
      #
