---
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile

    # build:
    #   context: .
    # image: soma1337/pipe_dream:latest
    volumes:
      - "./backend:/app"
    env_file:
      - "./backend/testenv"
    depends_on:
      - timescale
      - postgres
    networks:
      - dbnet
      - webnet
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ./sql/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5439:5432"  # Remapped to avoid conflict
    env_file:
      - "./backend/testenv"
    networks:
      - dbnet
    restart: always

  timescale:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - "timescale-data:/var/lib/postgresql/data"
      - "./sql/setup_timescale.sql:/setup_timescale.sql" 
      - ./sql/timescale/init.sql:/docker-entrypoint-initdb.d/init.sql
    # remapped because it was conflicting with local postgres
    ports:
      - "5438:5432"
    env_file:
      - ".env"
    environment:
      - RTE=${RTE}
      - POSTGRES_USER=${TS_POSTGRES_USER}  # Use .env variables
      - POSTGRES_PASSWORD=${TS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TS_POSTGRES_DB}
      - POSTGRES_HOST=${TS_POSTGRES_HOST}
    networks:
      - dbnet
    # command: ["bash", "entrypoint-timescale.sh"]

  market_data_service:
    build:
      context: ./market_data_service
    env_file:
      - ".env"
    environment:
      - RTE=${RTE}
      - POSTGRES_USER=${TS_POSTGRES_USER}  # Use .env variables
      - POSTGRES_PASSWORD=${TS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TS_POSTGRES_DB}
      - POSTGRES_HOST=${TS_POSTGRES_HOST}
    volumes:
      - ".:/opt/timescale_pull" 
    depends_on:
      - timescale
    networks:
      - dbnet


volumes:
  postgres-data:  
  timescale-data:

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge
  # frontend:
  #   build:
  #     context: ./frontend
  #     # dockerfile: Dockerfile
  #
  #   # volumes:
  #   #   - ".:/app"
  #   ports:
  #     - "3000:3000"
  #   # build:
  #   #   context: .
  #   # image: soma1337/pipe_dream:latest
  #   env_file:
  #     - "./backend/testenv"
  #   depends_on:
  #     - timescale
  #     - backend
  #   networks:
  #     - dbnet
  #     - webnet
      #
