---
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      - app

  app:
    build:
      context: ./backend
      # dockerfile: Dockerfile

    # build:
    #   context: .
      # image: soma1337/pipe_dream:latest
    volumes:
      - "./backend:/app"
    env_file:
      - "./backend/testenv"
    depends_on:
      - db
    networks:
      - dbnet
      - webnet

  db:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - "db-data:/var/lib/postgresql/data"
    # remapped because it was conflicting with local postgres
    ports:
      - "5438:5432"
    env_file:
      - "./backend/testenv"
    networks:
      - dbnet

  redis:
    container_name: redis
    image: redis:6.2-alpine

volumes:
  db-data:
  
networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge
