---
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile

    # build:
    #   context: .
    #   image: soma1337/cryptobackend:latest
    volumes:
      - ".:/app"
    env_file:
      - ".env-$RTE"
    depends_on:
      - db
    networks:
      - dbnet
      - webnet

  db:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - ".env-$RTE"
    networks:
      - dbnet

volumes:
  db-data:

networks:
  webnet:
    driver: bridge
  dbnet:
    driver: bridge
