services:
  timescale:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5435:5432"
    networks:
      - dbnet
    env_file:
      - .env 
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always


  python_program:
    build:
      context: .
      dockerfile: Dockerfile_python
    networks:
      - dbnet
    volumes:
      - ".:/app"
    depends_on:
      - timescale
    restart: always

networks:
  dbnet:
    driver: bridge

volumes:
  timescaledb_data:
