name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: dd
        run: |
          ls -la
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          # Install Docker Compose (ensure it's installed in the environment)
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check version to confirm successful installation
      # Build the Docker images with Docker Compose
      - name: Build Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      # Start services defined in docker-compose.yml
      - name: Start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      # Wait for services to be ready (adjust timing as needed)
      - name: Wait for services to be ready
        run: |
          # You might need to adjust the waiting logic depending on the services you're using
          sleep 30  # Waiting for the services to initialize, replace with better wait logic if necessary

      # Run the tests
      - name: Run tests
        run: |
          # Modify the command below to run the appropriate tests for your app
          docker-compose -f docker-compose.yml exec app pytest  # Replace 'app' with your service name and 'pytest' with your test command

      # Shut down and clean up Docker Compose services
      - name: Shut down Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down
