name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: dd
        run: |
          ls -la
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          # Install Docker Compose (ensure it's installed in the environment)
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      # Build the Docker images with Docker Compose
      - name: Build Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      # Start services defined in docker-compose.yml
      - name: Start Docker Compose services
        run: |
          RTE=test docker-compose up --abort-on-container-exit --exit-code-from app

